[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_upload.use_1200bps_touch = true
board_build.arduino.memory_type = qio_opi
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCONFIG_ESP32S3_DATA_CACHE_64KB=y
  -DBOARD_HAS_PSRAM
  -DCONFIG_SPIRAM=y
  -DCONFIG_SPIRAM_MODE_OCT=y
  -DCONFIG_SPIRAM_SPEED_80M=y
  -mfix-esp32-psram-cache-issue
lib_deps =
  links2004/WebSockets@^2.6.1
